#pragma config(Sensor, in1,    floorOneSensor, sensorLineFollower)
#pragma config(Sensor, in2,    floorTwoSensor, sensorLineFollower)
#pragma config(Sensor, in3,    floorThreeSensor, sensorLineFollower)
#pragma config(Sensor, dgtl1,  floorOneButton, sensorTouch)
#pragma config(Sensor, dgtl2,  floorTwoButton, sensorTouch)
#pragma config(Sensor, dgtl3,  floorThreeButton, sensorTouch)
#pragma config(Motor,  port1,           elevatordriver, tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//variable that counts the floors
int floorNumber;

//creates a function for each movement

//1-2
void oneTwo()
{
	while (SensorValue(floorTwoButton = 1) && (floorNumber = 1) //if on floor one and you push floor 2
	{
		startMotor(elevatordriver, 20); //start motor at low speed
		wait(3.75); //ESTIMATED TIME
	}
}
//2-3
//2-1
//2-3
//3-1
//3-2

void floorNumberFunction()
{
	while(true)
	{
		//floor counter function
		if(SensorValue(floorOneSensor) > 500)
		{
			floorNumber = 1;
		}
		if(SensorValue(floorTwoSensor) > 500)
		{
			floorNumber = 2;
		}
		if(SensorValue(floorThreeSensor) > 500)
		{
			floorNumber = 3;
		}
	}
}
task main()
{
	while(true)
	{
		floorNumberFunction();
		oneTwo();
	}
}
